name: Test Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose run web ./scripts/wait-for-it.sh elasticsearch_test:9200 -t 60
      - run: docker-compose run web poetry run pytest tests
